### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by Consti10** [Tarson/BasicMediaCodec#1]
Cool Project ! I am looking for some examples that do live streaming with camera2 and MediaCodec api's (not the old 'render to texture' stuff) and your project is one of the few that is simple enough.
I have plans to create a similar app like yours to allow streaming to [FPV_VR_OS](https://github.com/Consti10/FPV_VR_OS).
However, for lower latency I think using the NDK is required (tough there is even less documentation/examples) available.

**Comment by Tarson** [comment]
Thanks.
I'm novice in Android, and I just wanted to learn how to make streaming here. But I hate complicity of old API with tons of SemiPlanar420 etc... Just found simple surface conception 5 monthes ago.
I wrote some articles about photo, video, and  streaming from Android device, and getting this stream to JAVA application on PC. You can see it by google translation just for fun  (it is on Russian)

https://habr.com/ru/post/468083/
https://habr.com/ru/post/471774/
https://habr.com/ru/post/473036/
https://habr.com/ru/post/473840/

Regarding latency you can use such kees (for PC)

"--clock-jitter=100",
 "--live-caching=100",
 "--network-caching=500",

**Comment by Consti10** [comment]
Hello,
based on your source code I started a new project that right now has the improvements
a) help the user find the IP adress of the device data should be sent to
b) send data via ndk / UDP 
[LiveVideoStreamProducer](https://github.com/Consti10/LiveVideoStreamProducer)

**Comment by Tarson** [comment]
Hi
it is impossible, if you want to make direct transmission. You need to know IP of target device in advance.
It is no way to find it by transmitter. Sender may know only its own IP.
If you want to make so a you said, you need to set up special server in your net or in the WWW. And
each new device should be registrate there, as sender or receiver and give the server its own IP. Server stores this information in its memory,
After server send IP of receiver to sender, and then sender can start transmissions.

  
>Среда, 8 апреля 2020, 18:43 +03:00 от Consti10 <notifications@github.com>:
> 
> 
>Hello,
>based on your source code I started a new project that right now has the improvements
>a) help the user find the IP adress of the device data should be sent to
>b) send data via ndk / UDP
>LiveVideoStreamProducer
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
sip not
